### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio

### ISSUE THREAD

**Issue by ghost** [laravel-notification-channels/twilio#27]
Posting again as the original Laravel issue has been closed.

Laravel 5.4
"laravel-notification-channels/twilio": "^1.0"
Config file (services) is fine, as is .env.

Error:

```bash
[Illuminate\Contracts\Container\BindingResolutionException]                                    
Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio
```

Stack Trace:

```bash
[2017-03-15 22:13:57] local.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio in /Users/Alex/WEBHOSTS/FHMatchL5/vendor/laravel/framework/src/Illuminate/Container/Container.php:888
```

Stack trace:
```
[2017-03-15 22:13:57] local.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio in /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php:888

#0 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Illuminate\Container\Container->unresolvablePrimitive(Object(ReflectionParameter))
#1 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->resolvePrimitive(Object(ReflectionParameter))
#2 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->resolveDependencies(Array)
#3 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('Services_Twilio')
#4 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('Services_Twilio')
#5 /L5/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(702): Illuminate\Container\Container->make('Services_Twilio')
#6 /L5/vendor/laravel/framework/src/Illuminate/Container/Container.php(840): Illuminate\Foundation\Application->make('Services_Twilio')
```

**Comment by jamatheney** [comment]
I am having the same issue

**Comment by REBELinBLUE** [comment]
I fixed this a while ago, it was merged into master but doesn't seem that a new version has been released

**Comment by REBELinBLUE** [comment]
Oh, actually looks like v2 has been released with the fix

**Comment by jamatheney** [comment]
updating to v2 has solved the problem for me. thanks.

**Comment by zohaib-zix** [comment]
still have the same issue
