### ISSUE TITLE
Credentials are required to create a Client

### ISSUE THREAD

**Issue by ghost** [laravel-notification-channels/twilio#28]
Using latest package 2.0 with Laravel 5.4.

.env file:
```ini
TWILIO_SID=sidherecorrectly
TWILIO_TOKEN=tokenherecorrectly
TWILIO_FROM=numberherecorrectly
```

config/services.php:
```php
    'twilio' => [
        'account_sid' => env('TWILIO_SID'),
        'auth_token' => env('TWILIO_TOKEN'),
        'from' => env('TWILIO_FROM'), // optional
    ],
```

Error in log file:

```bash
[2017-03-30 22:35:28] development.ERROR: Twilio\Exceptions\ConfigurationException: Credentials are required to create a Client in /srv/site.com/dev/vendor/twilio/sdk/Twilio/Rest/Client.php:130
Stack trace:
#0 [internal function]: Twilio\Rest\Client->__construct(NULL, NULL, NULL, NULL, NULL, Array)
#1 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->newInstanceArgs(Array)
#2 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('Twilio\\Rest\\Cli...')
#3 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('Twilio\\Rest\\Cli...')
#4 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('Twilio\\Rest\\Cli...')
#5 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(840): Illuminate\Foundation\Application->make('Twilio\\Rest\\Cli...')
#6 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->resolveDependencies(Array)
#8 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('NotificationCha...')
#9 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('NotificationCha...')
#10 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('NotificationCha...')
#11 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(840): Illuminate\Foundation\Application->make('NotificationCha...')
#12 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#13 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(746): Illuminate\Container\Container->resolveDependencies(Array)
#14 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('NotificationCha...')
#15 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('NotificationCha...')
#16 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('NotificationCha...')
#17 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(137): Illuminate\Foundation\Application->make('NotificationCha...')
#18 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Support/Manager.php(63): Illuminate\Notifications\ChannelManager->createDriver('NotificationCha...')
#19 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Support\Manager->driver('NotificationCha...')
#20 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(site\Models\User), 'e9e724bb-c203-4...', Object(site\Notifications\FHApp\BookingReminder), 'NotificationCha...')
#21 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(51): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(site\Notifications\FHApp\BookingReminder), Array)
#22 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(57): Illuminate\Notifications\ChannelManager->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(site\Notifications\FHApp\BookingReminder), Array)
#23 [internal function]: Illuminate\Notifications\SendQueuedNotifications->handle(Object(Illuminate\Notifications\ChannelManager))
#24 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#25 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#27 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#28 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#29 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Illuminate\Notifications\SendQueuedNotifications))
#30 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Notifications\SendQueuedNotifications))
#31 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): Illuminate\Bus\Dispatcher->dispatchNow(Object(Illuminate\Notifications\SendQueuedNotifications), false)
#33 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(69): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#34 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#35 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\Queue\SyncQueue->push(Object(Illuminate\Notifications\SendQueuedNotifications))
#36 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(159): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(Illuminate\Notifications\SendQueuedNotifications))
#37 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(Illuminate\Notifications\SendQueuedNotifications))
#38 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(160): Illuminate\Bus\Dispatcher->dispatch(Object(Illuminate\Notifications\SendQueuedNotifications))
#39 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(61): Illuminate\Notifications\NotificationSender->queueNotification(Object(Illuminate\Database\Eloquent\Collection), Object(site\Notifications\FHApp\BookingReminder))
#40 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(site\Notifications\FHApp\BookingReminder))
#41 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(site\Models\User), Object(site\Notifications\FHApp\BookingReminder))
#42 /srv/site.com/dev/app/Console/Commands/SendReminders.php(53): site\Models\User->notify(Object(site\Notifications\FHApp\BookingReminder))
#43 [internal function]: site\Console\Commands\SendReminders->handle()
#44 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#45 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#46 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#47 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(531): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#48 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#49 /srv/site.com/dev/vendor/symfony/console/Command/Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#50 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#51 /srv/site.com/dev/vendor/symfony/console/Application.php(864): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#52 /srv/site.com/dev/vendor/symfony/console/Application.php(216): Symfony\Component\Console\Application->doRunCommand(Object(site\Console\Commands\SendReminders), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#53 /srv/site.com/dev/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 /srv/site.com/dev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#55 /srv/site.com/dev/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 {main}  

```

**Comment by LG0012** [comment]
I have the same problem, any solution?

**Comment by whackashoe** [comment]
https://github.com/whackashoe/twilio-notifications-channel

This solved it for me.. I was using the branch off of https://github.com/reganjohnson/twilio and just slightly modified it. Seems to be a bit of a hacky fix but I don't have time right now to test further & make a PR.

**Comment by majuansari** [comment]
Any solutions to the problem ?

**Comment by shahmir811** [comment]
Any solution ?

**Comment by alexciarlillo** [comment]
I can see the code was changed in this commit: https://github.com/laravel-notification-channels/twilio/commit/cd6fa05ca0a0548e5badd5e1db5a7a84a2013b69 but no explanation as to why. Is auth token no longer the preferred method for authenticating to Twilio?

EDIT, found this: https://github.com/laravel-notification-channels/twilio/pull/35

And I got our config working again by updating services like this:
```
'twilio' => [
        'account_sid' => env('TWILIO_ACCOUNT_SID'),
        'password' => env('TWILIO_AUTH_TOKEN'),
        'username' => env('TWILIO_USERNAME', ''),
        'from' => env('TWILIO_SMS_FROM_NUMBER'),
    ],
```

I kept the old environment variables. I really do not like how the names were changed for this PR as they really do not reflect the underlying data. When using the API we are not passing a username and password, we are passing tokens. Since we are still using the SID, I am just defaulting the username to blank string.

**Comment by cmgmyr** [comment]
you could also lock your `composer.json` file to the previous commit

```
"require": {
    "laravel-notification-channels/twilio": "dev-master#aacc86e5e075cccbe7e38924de6dde2457462e47"
}
```

**Comment by tylergets** [comment]
Whats going on with this? I tried @alexciarlillo's config but am still getting the error. I will submit a PR but it appears the Client class from Twilio does ask for a username and password

Update:
I was able to get it working by using
```PHP
'twilio' => [
        'account_sid' => env('TWILIO_ACCOUNT_SID'),
        'password' => env('TWILIO_AUTH_TOKEN'),
        'username' => env('TWILIO_ACCOUNT_SID'),
        'from' => env('TWILIO_SMS_FROM_NUMBER'),
    ],
```

**Comment by gregoriohc** [comment]
On the last release (2.0.2) I have changed the configuration parameters to support both (auth token or  username/password) authentication methods

**Comment by jminkler** [comment]
I still get this ... Twilio\Exceptions\ConfigurationException: Credentials are required to create a Client

'twilio' => [
        'auth_token' => env('TWILIO_AUTH_TOKEN'), // optional when using username and password
        'account_sid' => env('TWILIO_ACCOUNT_SID'),
        'from' => env('TWILIO_FROM'), // optional
    ],

etc ... have tried config:clear, anything else I can check?

**Comment by amirgee007** [comment]
**php artisan config:cache**

normally if we set all the variable in env file and it will not fetch client id from env so just need to config:cache and it will work.

working for me.......................

**Comment by davefrassoni** [comment]
env names were changed... who knows why. just update your env var names to:
**TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN**

**Comment by AhmedHdeawy** [comment]
this issue happens with me after upload the website on shared host and after run 
`php artisan config:cache`
on localhost
and uploaded the website again to host,
it works fine and sent sms

**Comment by isaacdarcilla** [comment]
Any solutions?

**Comment by hirenpatel1903** [comment]
Erorr:- **Credentials are required to create a Client**

**Comment by DevTiago** [comment]
Same here! :/

Well, my problem was easy to solve. On my controller i have this:

```
<?php

namespace App\Http\Controllers;

use App\Clients;
use Twilio\Rest\Client;
```

And on the method i was creating a new client to Twilio when i need to create is a new Client to save in my database.

So, just change from **$cli = new Client** to **$cli = new Clients** and problem solved!

**Comment by wrabit** [comment]
Is "TWILIO_AUTH_TOKEN" the "api secret"?
